FROM continuumio/anaconda3

ENV APP_HOME ./home
WORKDIR ${APP_HOME}
RUN conda config --append channels conda-forge
RUN conda install --quiet --yes \
    'mlflow' \
    'psycopg2' \
    'tensorflow==2.0.0'\
    'nodejs'
RUN pip install pylint ipywidgets bqplot

RUN jupyter nbextension enable --py widgetsnbextension --sys-prefix \
    && jupyter labextension install @jupyter-widgets/jupyterlab-manager


#RUN git clone https://github.com/MChrys/QuickSign.git 
RUN pwd;ls
COPY GUI_QuickSign.ipynb .
RUN jupyter trust GUI_QuickSign.ipynb
COPY project project
COPY display_log display_log
VOLUME ["/home"]
#RUN conda install jupyter 
CMD jupyter notebook --ip=0.0.0.0 --port=8887 --no-browser --allow-root 