version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    ports:
      - "8887:8887"
    depends_on: 
      - mlflow
    environment: 
      MLFLOW_TRACKING_URI: 'http://mlflow:5000'
  mlflow:
    build:
      context: ./ml-flow-docker
    expose: 
      - "5000"
    ports:
      - "5000:5000"
    depends_on: 
      - postgres
  postgres:
    build:
      context: ./postgres-docker
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'secret'
    ports: 
      - "5432:5432"